"""
You find yourselves on the roof of a top-secret Easter Bunny installation.

While The Historians do their thing, you take a look at the familiar huge antenna. Much to your surprise, it seems to have been reconfigured to emit a signal that makes people 0.1% more likely to buy Easter Bunny brand Imitation Mediocre Chocolate as a Christmas gift! Unthinkable!

Scanning across the city, you find that there are actually many such antennas. Each antenna is tuned to a specific frequency indicated by a single lowercase letter, uppercase letter, or digit. You create a map (your puzzle input) of these antennas. For example:

............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
The signal only applies its nefarious effect at specific antinodes based on the resonant frequencies of the antennas. In particular, an antinode occurs at any point that is perfectly in line with two antennas of the same frequency - but only when one of the antennas is twice as far away as the other. This means that for any pair of antennas with the same frequency, there are two antinodes, one on either side of them.

So, for these two antennas with frequency a, they create the two antinodes marked with #:

..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
Adding a third antenna with the same frequency creates several more antinodes. It would ideally add four antinodes, but two are off the right side of the map, so instead it adds only two:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........
Antennas with different frequencies don't create antinodes; A and a count as different frequencies. However, antinodes can occur at locations that contain antennas. In this diagram, the lone antenna with frequency capital A creates no antinodes but has a lowercase-a-frequency antinode at its location:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......A...
..........
..........
The first example has antennas with two different frequencies, so the antinodes they create look like this, plus an antinode overlapping the topmost A-frequency antenna:

......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#.
Because the topmost A-frequency antenna overlaps with a 0-frequency antinode, there are 14 total unique locations that contain an antinode within the bounds of the map.

Calculate the impact of the signal. How many unique locations within the bounds of the map contain an antinode?
"""

from common_functions import get_real_data, Grid


def calculate_distance_between_points(pos_a: tuple[int, int], pos_b: tuple[int, int]) -> tuple[int, int]:
    x_distance = pos_a[1] - pos_b[1]
    y_distance = pos_a[0] - pos_b[0]
    return x_distance, y_distance


if __name__ == "__main__":
    data = get_real_data(False)
    print(data)
    letter_position = {}
    antenna_grid = Grid(data)
    # Grab the max bounds of the grid so we can establish whether nodes are inside it or not
    max_x = antenna_grid.width
    max_y = antenna_grid.height
    print(f"Max grid size: {max_x} by {max_y}")
    # Get the positions of all countable characters to find pairs
    for item in antenna_grid.grid:
        value = antenna_grid.grid[item]
        if value == ".":
            continue
        if value in letter_position.keys():
            letter_position[value].append(item)
        else:
            letter_position[value] = [item]
    print(letter_position)
    antenna_grid.print_grid()
    node_counter = 0
    # Iterate over letters, comparing pairs to establish whether they create nodes or not
    for letter in letter_position:
        print(f"Checking {letter}")
        for i in range(len(letter_position[letter])):
            pos_a = letter_position[letter][i]
            pos_b = letter_position[letter][i - 1]
            antenna_grid.grid[pos_a] = "1"
            antenna_grid.grid[pos_b] = "2"
            antenna_grid.print_grid()
            antenna_grid.grid[pos_a] = letter
            antenna_grid.grid[pos_b] = letter
            x_dist, y_dist = calculate_distance_between_points(pos_a, pos_b)
            print(f"Letter: {letter}, A:{pos_a}, B:{pos_b} - x: {x_dist}, y: {y_dist}")
            alt_x = x_dist * -1
            alt_y = y_dist * -1
            pos_a_node = (pos_a[1] - x_dist, pos_a[0] - y_dist)
            pos_a_antinode = (pos_a[1] - alt_x, pos_a[0] - alt_y)
            pos_b_node = (pos_b[1] - x_dist, pos_b[0] - y_dist)
            pos_b_antinode = (pos_b[1] - alt_x, pos_b[0] - alt_y)
            nodes = [pos_a_node, pos_a_antinode, pos_b_node, pos_b_antinode]
            print(f"Node positions: {nodes}")

            for node in nodes:
                if antenna_grid.inside_grid(node) and antenna_grid.grid[node] == ".":
                    antenna_grid.grid[node] = "#"
                    node_counter += 1
    antenna_grid.print_grid(include_row_nums=True)
    print(f"Node count: {node_counter}")
